# Importing all Main libraries


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



# DATA PRE-PROCESSING

In [ ]:
df=pd.read_csv("Desktop/aug_test.csv")

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.sample(10)

In [ ]:
category=["LOW","MID","HIGH"]
df["CTC"]= np.random.choice(category,size=len(df))

In [ ]:
df.columns


In [ ]:
for col in df.columns:
    print(repr(col))

In [ ]:
df.drop(columns=[
    "enrollee_id",
    "city",
    "city_development_index",
    "gender",
    "experience",
    "company_size",
    "company_type",
    "last_new_job",
    "training_hours"   # check spelling carefully
], inplace=True)

In [ ]:
df.sample(15)


In [ ]:
df["education_level"].unique()

In [42]:
df.dropna(inplace=True)

# ORDINAL ENCODING

In [44]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,Y_train, Y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)


In [45]:
X_train

relevent_experience enrolled_university education_level  \
1888  Has relevent experience       no_enrollment        Graduate   
1762   No relevent experience       no_enrollment         Masters   
714   Has relevent experience       no_enrollment         Masters   
1577  Has relevent experience       no_enrollment             Phd   
1845   No relevent experience    Full time course        Graduate   
...                       ...                 ...             ...   
591   Has relevent experience       no_enrollment        Graduate   
1279  Has relevent experience       no_enrollment        Graduate   
1476  Has relevent experience       no_enrollment        Graduate   
394   Has relevent experience       no_enrollment         Masters   
1676  Has relevent experience       no_enrollment        Graduate   

     major_discipline  
1888             STEM  
1762             STEM  
714              STEM  
1577             STEM  
1845             STEM  
...               ...  
591              STEM  
1279             STEM  
1476             STEM  
394              STEM  
1676            Other  

[1437 rows x 4 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder


In [ ]:
df["major_discipline"].unique()

In [ ]:
oe=OrdinalEncoder(categories=[["No relevent experience","Has relevent experience"],
                              ["no_enrollment","Part time course","Full time course"],
                             ["Primary School","High School","Graduate","Masters","Phd"],
                              ['No Major','Other','Arts','Humanities','Business Degree','STEM']])

In [47]:
oe.fit(X_train)

OrdinalEncoder(categories=[['No relevent experience',
                            'Has relevent experience'],
                           ['nan', 'no_enrollment', 'Part time course',
                            'Full time course'],
                           ['nan', 'Primary School', 'High School', 'Graduate',
                            'Masters', 'Phd'],
                           ['nan', 'No Major', 'Other', 'Arts', 'Humanities',
                            'Business Degree', 'STEM']])

In [48]:
X_train=oe.transform(X_train)

In [49]:
X_train

array([[1., 1., 3., 6.],
       [0., 1., 4., 6.],
       [1., 1., 4., 6.],
       ...,
       [1., 1., 3., 6.],
       [1., 1., 4., 6.],
       [1., 1., 3., 2.]])

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le=LabelEncoder()

In [54]:
le.fit(Y_train)

LabelEncoder()

In [55]:
le.fit(Y_test)

LabelEncoder()

In [57]:
oe.fit(X_test)

OrdinalEncoder(categories=[['No relevent experience',
                            'Has relevent experience'],
                           ['nan', 'no_enrollment', 'Part time course',
                            'Full time course'],
                           ['nan', 'Primary School', 'High School', 'Graduate',
                            'Masters', 'Phd'],
                           ['nan', 'No Major', 'Other', 'Arts', 'Humanities',
                            'Business Degree', 'STEM']])

In [58]:
Y_train

1888     LOW
1762     MID
714     HIGH
1577     LOW
1845     LOW
        ... 
591      MID
1279    HIGH
1476     LOW
394     HIGH
1676    HIGH
Name: CTC, Length: 1437, dtype: object

In [59]:
Y_train=le.transform(Y_train)

In [60]:
Y_train

array([1, 2, 0, ..., 1, 0, 0])

In [62]:
le.classes_

array(['HIGH', 'LOW', 'MID'], dtype=object)

In [4]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
ohe=OneHotEncoder()
df=pd.read_csv("Desktop/aug_test.csv")

In [7]:
df.sample(5)

enrollee_id      city  city_development_index gender  \
2109        13962   city_36                   0.893   Male   
1395        32521   city_28                   0.939   Male   
2030        13232  city_160                   0.920    NaN   
348          9021  city_103                   0.920    NaN   
5             217   city_23                   0.899   Male   

          relevent_experience enrolled_university education_level  \
2109  Has relevent experience       no_enrollment         Masters   
1395  Has relevent experience       no_enrollment     High School   
2030  Has relevent experience       no_enrollment        Graduate   
348   Has relevent experience       no_enrollment        Graduate   
5      No relevent experience    Part time course         Masters   

     major_discipline experience company_size    company_type last_new_job  \
2109       Humanities         20        50-99         Pvt Ltd            1   
1395              NaN          5          NaN             NaN            1   
2030             STEM         14      100-500         Pvt Ltd            2   
348              STEM        >20        10/49  Funded Startup           >4   
5                STEM         10          NaN             NaN            2   

      training_hours  
2109              26  
1395               6  
2030              18  
348              248  
5                 12

In [8]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:13],df.iloc[:,-1],test_size=0.2)

In [9]:
x_train=ohe.fit_transform(x_train[["relevent_experience","education_level"]]).toarray()

In [10]:
x_test=ohe.transform(x_test[["relevent_experience","education_level"]]).toarray()

In [11]:
x_train

array([[1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])